const G = {};
for (const g of ['SillyTavern','$','jQuery','toastr','localStorage','sessionStorage','console','document','window','navigator','fetch','setTimeout','clearTimeout','setInterval','clearInterval','requestAnimationFrame','structuredClone','AbortController','alert','confirm','prompt','crypto','performance','queueMicrotask','TextEncoder','TextDecoder','Blob','URL','FileReader','Image','MutationObserver','getComputedStyle','DOMParser','Node','Element','HTMLElement','Event','CustomEvent','process','require','module','__dirname','globalThis']) G[g] = 'readonly';
export default [
  {
    files: ['**/*.js', '**/*.mjs'],
    languageOptions: { ecmaVersion: 2023, sourceType: 'module', globals: G },
    linterOptions: { reportUnusedDisableDirectives: true },
    rules: {
      'no-undef': 'error',
      'no-redeclare': 'error',
      'no-dupe-keys': 'error',
      'no-dupe-args': 'error',
      'no-dupe-else-if': 'error',
      'no-duplicate-case': 'error',
      'no-unreachable': 'error',
      'no-const-assign': 'error',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'no-cond-assign': 'error',
      'no-constant-condition': 'error',
      'no-empty-pattern': 'error',
      'no-fallthrough': 'error',
      'no-obj-calls': 'error',
      'no-sparse-arrays': 'error',
      'no-async-promise-executor': 'error',
      'no-compare-neg-zero': 'error',
      'no-invalid-regexp': 'error',
      'no-misleading-character-class': 'error',
      'no-prototype-builtins': 'off',
      'no-control-regex': 'off',
      'no-useless-escape': 'warn',
      'require-atomic-updates': 'error',
      'no-unused-vars': ['warn', { args: 'none', varsIgnorePattern: '^_' }],
    },
  },
];
